server:
  port: 8888


spring:
  application:
    name: spring-cloud-config-server
  cloud:
    config:
      server:
        git:
          uri: https://github.com/somensarangi/spring-cloud-config-repo.git
          default-label: master   # <--- set this to your repo's branch
          search-paths: configs
          refresh-rate: 0



management:
  endpoints:
    web:
      exposure:
        include: "*"